name: CI

on:
  push:
    branches: [master]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Build php7 image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: sitkoru/minio
          tag_with_ref: true
          tags: latest
